# Use official Python image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install Flask
RUN pip install flask

# Copy backend files
COPY . .

# Expose port
EXPOSE 5000

# Run backend app
CMD ["python", "app.py"]

