apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv2
  labels:
    app: prometheus
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/prometheus

