@Library('EbrahimSharedLib') _

pipeline {
    agent { label 'slave' }

    stages {
        stage('RunUnitTest') { steps { runUnitTest() } }
        stage('BuildApp') { steps { buildApp() } }
        stage('BuildImage') { steps { buildImage() } }
        stage('ScanImage') { steps { scanImage() } }
        stage('PushImage') { steps { pushImage() } }
        stage('RemoveImageLocally') { steps { removeImageLocally() } }
        stage('DeployOnK8s') { steps { deployOnK8s() } }
    }

    post { always { echo "✅ CI/CD Pipeline finished successfully!" } }
}
