---
- name: Automated Web Server Configuration
  hosts: webservers
  become: true
  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure Nginx service is running and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Customize the web page
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>Welcome to Lab 2</title></head>
          <body>
          <h1>Hello from Ansible Web Server!</h1>
          </body>
          </html>
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Verify Nginx is serving the page
      ansible.builtin.uri:
        url: http://localhost
        return_content: yes
      register: result

    - name: Show verification result
      ansible.builtin.debug:
        var: result.content

