pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'dockerhub' // تم تغييره هنا
        IMAGE_NAME = 'ebrahimrhh/demo:latest'
        GIT_REPO = 'https://github.com/Ibrahim-Adel15/Jenkins_App.git'
        GIT_BRANCH = 'main'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: "${GIT_BRANCH}", url: "${GIT_REPO}"
            }
        }

        stage('Build App (Maven)') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${IMAGE_NAME} ."
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${DOCKERHUB_CREDENTIALS}", 
                                                  passwordVariable: 'DOCKER_PASSWORD', 
                                                  usernameVariable: 'DOCKER_USERNAME')]) {
                    sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
                    sh "docker push ${IMAGE_NAME}"
                }
            }
        }

        stage('Delete Local Image') {
            steps {
                echo 'Deleting local Docker image...'
                sh "docker rmi ${IMAGE_NAME}"
            }
        }

        stage('Create deployment.yaml') {
            steps {
                echo 'Creating deployment.yaml in workspace...'
                writeFile file: 'deployment.yaml', text: """
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: ${IMAGE_NAME}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
"""
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                echo 'Deploying new image to Kubernetes...'
                sh "kubectl apply -f deployment.yaml"
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished (Always section).'
        }
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
